### ISSUE TITLE
Poor documentation

### ISSUE THREAD

**Issue by hanusek** [slowtec/msr#16]
Hello!
Poor documentation.
I found this project on the web.
I want to get more details about this project. 

Is it softPLC like codesys/[straton](https://straton-plc.com/)/[rustmatic](https://github.com/NOP0/rustmatic)?

**Comment by flosse** [comment]
> Hello!
> Poor documentation.

Thank you for this "appreciative" feedback.

With a slightly more precise question and a little respect, your request could even result in a successful response.
Maybe you take a little bit more time to formulate your question and you might get a qualified feedback.
